apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-webserver
  namespace: application-1
spec:
  podSelector:
    matchLabels:
      app: webserver
  policyTypes:
  - Ingress
