apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomalous
  namespace: application-1
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: apache
          image: quay.io/bitnami/apache:2.4.46
          ports:
            - containerPort: 8080
              name: webserver
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
